name: Python data-flow Tests

on: [ push ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install modules
        run: pip install -r requirements.txt && pip install -r requirements.dev.txt
      - name: Tests
        run: PYTHONPATH=. pytest --cov=data_flow --cov-report term
      - name: Lint
        run: pflake8 data_flow/